### ISSUE TITLE
Gracefully handle failures when reading zone humidity

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/roth-modbus-mqtt#3]
```
Dec 24 08:45:05 roth-modbus-mqtt node[250667]: 2024-12-24T08:45:05.237Z [modbus] debug: Reading holding register address 124, length 1
Dec 24 08:45:06 roth-modbus-mqtt node[250667]: 2024-12-24T08:45:06.090Z [modbus] error: Failed to read holding register address 124, length 1
Dec 24 08:45:06 roth-modbus-mqtt node[250667]: /opt/roth-modbus-mqtt/node_modules/modbus-serial/index.js:435
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:             error = new Error("Modbus exception " + errorCode + ": " + (modbusErrorMessages[errorCode] || "Unknown error"));
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:                     ^
Dec 24 08:45:06 roth-modbus-mqtt node[250667]: Error: Modbus exception 1: Illegal function (device does not support this read/write function)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at ModbusRTU._onReceive (/opt/roth-modbus-mqtt/node_modules/modbus-serial/index.js:435:21)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at TcpPort.emit (node:events:518:28)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at Socket.<anonymous> (/opt/roth-modbus-mqtt/node_modules/modbus-serial/ports/tcpport.js:122:22)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at Socket.emit (node:events:518:28)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at addChunk (node:internal/streams/readable:561:12)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at Readable.push (node:internal/streams/readable:392:5)
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:     at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
Dec 24 08:45:06 roth-modbus-mqtt node[250667]:   modbusCode: 1
Dec 24 08:45:06 roth-modbus-mqtt node[250667]: }
Dec 24 08:45:06 roth-modbus-mqtt node[250667]: Node.js v22.11.0
```

Seems to occur mainly after rebooting the controller. After a while things stabilize and the register start returning values again.

**Comment by Jalle19** [comment]
Turns out quite a few register reads can fail during startup, I don't think there's much that can be done about that except to document the behavior
